package types

import (
	"fmt"
	"time"
)

// Payload represents a Mythic payload (generated agent binary).
type Payload struct {
	ID              int                `json:"id"`
	UUID            string             `json:"uuid"`
	Description     string             `json:"description"`
	OperatorID      int                `json:"operator_id"`
	OperationID     int                `json:"operation_id"`
	CreationTime    time.Time          `json:"creation_time"`
	PayloadTypeID   int                `json:"payload_type_id"`
	OS              string             `json:"os"`
	BuildContainer  string             `json:"build_container"`
	BuildPhase      string             `json:"build_phase"`
	BuildMessage    string             `json:"build_message"`
	BuildStderr     string             `json:"build_stderr"`
	BuildStdout     string             `json:"build_stdout"`
	CallbackAlert   bool               `json:"callback_alert"`
	AutoGenerated   bool               `json:"auto_generated"`
	Deleted         bool               `json:"deleted"`
	CallbacksCount  int                `json:"callbacks_count"`
	TagStr          string             `json:"tag"`
	PayloadType     *PayloadType       `json:"payloadtype,omitempty"`
	Operator        *Operator          `json:"operator,omitempty"`
	BuildParameters []BuildParameter   `json:"build_parameters,omitempty"`
	C2Profiles      []PayloadC2Profile `json:"c2profiles,omitempty"`
	Commands        []PayloadCommand   `json:"commands,omitempty"`
}

// PayloadType represents a type of payload (agent) available in Mythic.
type PayloadType struct {
	ID                  int       `json:"id"`
	Name                string    `json:"name"`
	FileExtension       string    `json:"file_extension"`
	Author              string    `json:"author"`
	WrapperMode         bool      `json:"wrapper"`
	Note                string    `json:"note"`
	SupportsDynamicLoad bool      `json:"supports_dynamic_loading"`
	BuildURL            string    `json:"build_url"`
	ExternalURL         string    `json:"external_url"`
	CreationTime        time.Time `json:"creation_time"`
	Deleted             bool      `json:"deleted"`
	ContainerRunning    bool      `json:"container_running"`
	OS                  string    `json:"mythic_encrypts"` // Actually the OS field in GraphQL
	SupportedC2Profiles []string  `json:"supported_c2_profiles,omitempty"`
}

// PayloadCommand represents a command available in a payload.
type PayloadCommand struct {
	ID          int    `json:"id"`
	CommandID   int    `json:"command_id"`
	PayloadID   int    `json:"payload_id"`
	Version     int    `json:"version"`
	CommandName string `json:"cmd"`
}

// PayloadC2Profile represents a C2 profile configured for a payload.
type PayloadC2Profile struct {
	ID            int                    `json:"id"`
	PayloadID     int                    `json:"payload_id"`
	C2ProfileID   int                    `json:"c2_profile_id"`
	C2ProfileName string                 `json:"c2_profile_name"`
	Parameters    map[string]interface{} `json:"parameters,omitempty"`
}

// BuildParameter represents a build parameter for a payload.
type BuildParameter struct {
	Name        string      `json:"name"`
	Value       interface{} `json:"value"`
	Description string      `json:"description,omitempty"`
}

// PayloadOnHost represents tracking of a payload deployed on a host.
type PayloadOnHost struct {
	ID          int       `json:"id"`
	HostID      int       `json:"host_id"`
	PayloadID   int       `json:"payload_id"`
	OperationID int       `json:"operation_id"`
	TaskID      *int      `json:"task_id,omitempty"`
	Timestamp   time.Time `json:"timestamp"`
	Deleted     bool      `json:"deleted"`
	Host        string    `json:"host,omitempty"`
	Payload     *Payload  `json:"payload,omitempty"`
}

// CreatePayloadRequest represents a request to build a new payload.
type CreatePayloadRequest struct {
	PayloadType     string                 `json:"payload_type"`
	OS              string                 `json:"os,omitempty"`
	Description     string                 `json:"description,omitempty"`
	Filename        string                 `json:"filename,omitempty"`
	Commands        []string               `json:"commands,omitempty"`
	C2Profiles      []C2ProfileConfig      `json:"c2_profiles,omitempty"`
	BuildParameters map[string]interface{} `json:"build_parameters,omitempty"`
	Tag             string                 `json:"tag,omitempty"`
	SelectedOS      string                 `json:"selected_os,omitempty"`
	WrapperPayload  string                 `json:"wrapped_payload,omitempty"` // UUID of payload to wrap
}

// C2ProfileConfig represents C2 profile configuration for payload creation.
type C2ProfileConfig struct {
	Name       string                 `json:"name"`
	Parameters map[string]interface{} `json:"parameters,omitempty"`
}

// UpdatePayloadRequest represents a request to update payload settings.
type UpdatePayloadRequest struct {
	UUID          string  `json:"uuid"`
	Description   *string `json:"description,omitempty"`
	CallbackAlert *bool   `json:"callback_alert,omitempty"`
	Deleted       *bool   `json:"deleted,omitempty"`
}

// RebuildPayloadRequest represents a request to rebuild a payload.
type RebuildPayloadRequest struct {
	PayloadUUID string `json:"payload_uuid"`
}

// ExportPayloadConfigResponse represents the exported payload configuration.
type ExportPayloadConfigResponse struct {
	Config string `json:"config"`
}

// String returns a string representation of a Payload.
func (p *Payload) String() string {
	status := "building"
	if p.BuildPhase == "success" {
		status = "ready"
	} else if p.BuildPhase == "error" {
		status = "failed"
	}

	return fmt.Sprintf("%s (%s, %s)", p.UUID, p.OS, status)
}

// IsReady returns true if the payload build completed successfully.
func (p *Payload) IsReady() bool {
	return p.BuildPhase == "success"
}

// IsFailed returns true if the payload build failed.
func (p *Payload) IsFailed() bool {
	return p.BuildPhase == "error"
}

// IsBuilding returns true if the payload is still building.
func (p *Payload) IsBuilding() bool {
	return p.BuildPhase == "building" || p.BuildPhase == "submitted"
}

// String returns a string representation of a PayloadType.
func (pt *PayloadType) String() string {
	return fmt.Sprintf("%s (%s)", pt.Name, pt.FileExtension)
}

// String returns a string representation of a PayloadOnHost.
func (poh *PayloadOnHost) String() string {
	host := poh.Host
	if host == "" {
		host = fmt.Sprintf("Host ID %d", poh.HostID)
	}
	return fmt.Sprintf("Payload %d on %s", poh.PayloadID, host)
}
