linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

  gosec:
    excludes:
      - G104  # Audit errors not checked (too many false positives)
      - G402  # TLS InsecureSkipVerify (we need this for self-signed certs)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

    - path: tests/
      linters:
        - gosec
        - errcheck

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
